site_name: PnP/PnPjs
docs_dir: 'docs'
nav:
  - Home: 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'Transition Guide': 'transition-guide.md'
  - General:
    - 'Getting Started': 'getting-started.md'
    - 'Transition Guide': 'transition-guide.md'
    - 'Contributing': 'getting-started-dev.md'
    - 'Npm Scripts': 'npm-scripts.md'
    - 'Debugging': 'debugging.md'
    - 'Debugging Tests': 'debug-tests.md'    
    - 'Install Beta Versions': 'beta-versions.md'    
    - 'SPFx On-Premises 2016': 'SPFx-On-Premesis-2016.md'
    - 'Building Docs': 'documentation.md'
  - 'Library Concepts':
    - 'Custom Bundle': 'concepts/custom-bundle.md'
    - 'IE11 Mode': 'concepts/ie11-mode.md'
    - 'Invokables': 'concepts/invokable.md'
    - 'Polyfills': 'concepts/polyfill.md'
    - 'Selective Imports': 'concepts/selective-imports.md'
    - 'Settings': 'concepts/settings.md'
  - Packages:
    - Packages: 'packages.md'
    - adaljsclient:
      - index: 'adaljsclient/index.md'
      - 'client': 'adaljsclient/adalclient.md'
    - common:
      - common: 'common/index.md'
      - collections: 'common/collections.md'
      - 'Custom HttpClientImpl': 'common/custom-httpclientimpl.md'
      - libconfig: 'common/libconfig.md'
      - netutil: 'common/netutil.md'
      - storage: 'common/storage.md'
      - util: 'common/util.md'
    - config-store:
      - config-store: 'config-store/index.md'
      - configuration: 'config-store/configuration.md'
      - providers: 'config-store/providers.md'
    - graph: 
      - graph: 'graph/index.md'
      - contacts: 'graph/contacts.md'
      - 'directory objects': 'graph/directoryobjects.md'
      - invitations: 'graph/invitations.md'
      - onedrive: 'graph/onedrive.md'
      - planner: 'graph/planner.md'
      - subscriptions: 'graph/subscriptions.md'
      - teams: 'graph/teams.md'
      - teams: 'graph/users.md'
    - logging: 'logging/index.md'
    - nodejs:
      - nodejs: 'nodejs/index.md'
      - SPFetchClient: 'nodejs/sp-fetch-client.md'     
      - AdalFetchClient: 'nodejs/adal-fetch-client.md'
      - BearerTokenFetchClient: 'nodejs/bearer-token-fetch-client.md'       
      - ProviderHostedRequestContext: 'nodejs/provider-hosted-app.md'
    - odata:
      - odata: 'odata/index.md'
      - caching: 'odata/caching.md'
      - core: 'odata/core.md'
      - 'OData Batching': 'odata/odata-batch.md'
      - 'Extending an OData library': 'odata/extensions.md'
      - Parsers: 'odata/parsers.md'
      - Pipeline: 'odata/pipeline.md'
      - Queryable: 'odata/queryable.md'
    - sp:
      - sp: 'sp/index.md'
      - 'Alias Parameters': 'sp/alias-parameters.md'
      - 'ALM api': 'sp/alm.md'
      - Attachments: 'sp/attachments.md'
      - 'Client-side Pages': 'sp/clientside-pages.md'
      - 'Comments and Likes': 'sp/comments-likes.md'
      - 'Content Types': 'sp/content-types.md'
      - 'Entity Merging': 'sp/entity-merging.md'
      - Features: 'sp/features.md'
      - Fields: 'sp/fields.md'
      - Files: 'sp/files.md'
      - Folders: 'sp/folders.md'
      - Forms: 'sp/forms.md'
      - Hubsites: 'sp/hubsites.md'
      - 'List Items': 'sp/items.md'
      - Lists: 'sp/lists.md'      
      - 'Navigation Service': 'sp/navigation-service.md'
      - Permissions: 'sp/permissions.md'
      - Profiles: 'sp/profiles.md'
      - 'Regional Settings': 'sp/regional-settings.md'
      - 'Related Items': 'sp/related-items.md'
      - Search: 'sp/search.md'
      - Security: 'sp/security.md'
      - Search: 'sp/search.md'
      - Sharing: 'sp/sharing.md'
      - 'Site Designs': 'sp/site-designs.md'
      - 'Site Groups': 'sp/site-groups.md'
      - 'Site Scripts': 'sp/site-scripts.md'
      - 'Site Users': 'sp/site-users.md'
      - Sites: 'sp/sites.md'
      - Social: 'sp/social.md'
      - 'SP.Utilities.Utility': 'sp/sp-utilities-utility.md'
      - Subscriptions: 'sp/subscriptions.md'
      - 'Tenant Properties': 'sp/tenant-properties.md'
      - 'User custom actions': 'sp/user-custom-actions.md'      
      - Views: 'sp/views.md'
      - Webs: 'sp/webs.md'
    - sp-addinhelpers:
      - sp-addinhelpers: 'sp-addinhelpers/index.md'
      - SPRequestExecutorClient:  'sp-addinhelpers/sp-request-executor-client.md'
      - SPRestAddIn: 'sp-addinhelpers/sp-rest-addin.md'
theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
    primary: 'blue'
  logo: 'docs/img/Logo.png'
  feature:
    tabs: true
extra_css:
  - 'docs/css/extra.css'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
plugins:
  - search
  - markdownextradata
extra:
  version: '2.0.0-7'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/officedevpnp'
    - type: 'youtube'
      link: 'http://aka.ms/sppnp-videos'
    - type: 'link'
      link: 'https://aka.ms/sppnp'
repo_url: http://github.com/pnp/pnpjs
edit_uri: tree/dev/docs
site_url: https://pnp.github.io/pnpjs/
